variable "aws_region" {
  description = "AWS region to deploy resources"
  type        = string
  default     = "us-east-1"
}

variable "enable_vpc" {
  description = "Whether to create VPC (set false for free demo)"
  type        = bool
  default     = false
}

variable "enable_eks" {
  description = "Whether to create EKS cluster (set false for free demo)"
  type        = bool
  default     = false
}

variable "enable_rds" {
  description = "Whether to create RDS instance (set false for free demo)"
  type        = bool
  default     = false
}

variable "environment" {
  description = "Environment name (e.g., dev, staging, prod)"
  type        = string
  default     = "dev"
}

variable "vpc_cidr" {
  description = "CIDR block for VPC"
  type        = string
  default     = "10.0.0.0/16"
}

variable "availability_zones" {
  description = "List of availability zones"
  type        = list(string)
  default     = ["us-east-1a", "us-east-1b", "us-east-1c"]
}

variable "private_subnet_cidrs" {
  description = "CIDR blocks for private subnets"
  type        = list(string)
  default     = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
}

variable "public_subnet_cidrs" {
  description = "CIDR blocks for public subnets"
  type        = list(string)
  default     = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]
}

variable "eks_instance_types" {
  description = "Instance types for EKS worker nodes"
  type        = list(string)
  default     = ["t3.medium"]
}

variable "eks_desired_size" {
  description = "Desired size of EKS worker node group"
  type        = number
  default     = 2
}

variable "eks_min_size" {
  description = "Minimum size of EKS worker node group"
  type        = number
  default     = 1
}

variable "eks_max_size" {
  description = "Maximum size of EKS worker node group"
  type        = number
  default     = 4
}

variable "root_account_id" {
  description = "(Optional) Root AWS account id used for organization bootstrap. Replace with your root account when running organization provisioning."
  type        = string
  default     = "000000000000"
}

variable "company_domain" {
  description = "(Optional) Company domain for autogenerated account emails"
  type        = string
  default     = "example.com"
}

variable "rds_instance_class" {
  description = "RDS instance class for demo"
  type        = string
  default     = "db.t3.micro"
}

variable "rds_allocated_storage" {
  description = "Allocated storage for RDS in GB"
  type        = number
  default     = 20
}

variable "allowed_regions" {
  description = "Allowed AWS regions for organization policy"
  type        = list(string)
  default     = ["us-east-1"]
}